export const word_to_found = [
  "swift",
  "kotlin",
  "objectivec",
  "variable",
  "java",
  "mobile"
]

export const first_data_grid = [
    { key: "A" },
    { key: "b" },
    { key: "c" },
    { key: "d" },
    { key: "e" },
    { key: "f" },
    { key: "g" },
    { key: "h" },
    { key: "i" },
    { key: "j" },
    { key: "A" },
    { key: "b" },
    { key: "c" },
    { key: "d" },
    { key: "e" },
    { key: "f" },
    { key: "g" },
    { key: "h" },
    { key: "i" },
    { key: "j" },
    { key: "A" },
    { key: "b" },
    { key: "c" },
    { key: "m" },
    { key: "o" },
    { key: "b" },
    { key: "i" },
    { key: "l" },
    { key: "e" },
    { key: "j" },
    { key: "A" },
    { key: "b" },
    { key: "c" },
    { key: "d" },
    { key: "e" },
    { key: "f" },
    { key: "g" },
    { key: "h" },
    { key: "i" },
    { key: "j" },
    { key: "A" },
    { key: "b" },
    { key: "v" },
    { key: "a" },
    { key: "r" },
    { key: "i" },
    { key: "a" },
    { key: "b" },
    { key: "l" },
    { key: "e" },
    { key: "j" },
    { key: "a" },
    { key: "v" },
    { key: "a" },
    { key: "e" },
    { key: "f" },
    { key: "g" },
    { key: "h" },
    { key: "i" },
    { key: "j" },
    { key: "o" },
    { key: "b" },
    { key: "j" },
    { key: "e" },
    { key: "c" },
    { key: "t" },
    { key: "i" },
    { key: "v" },
    { key: "e" },
    { key: "c" },
    { key: "A" },
    { key: "b" },
    { key: "c" },
    { key: "d" },
    { key: "e" },
    { key: "f" },
    { key: "g" },
    { key: "h" },
    { key: "d" },
    { key: "e" },
    { key: "s" },
    { key: "w" },
    { key: "i" },
    { key: "f" },
    { key: "t" },
    { key: "f" },
    { key: "g" },
    { key: "h" },
    { key: "i" },
    { key: "j" },
    { key: "A" },
    { key: "k" },
    { key: "o" },
    { key: "t" },
    { key: "l" },
    { key: "i" },
    { key: "n" },
    { key: "h" },
    { key: "i" },
    { key: "j" }
  ];